# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 18:19
from __future__ import unicode_literals

from django.db import migrations
from clemson_google_app.models import ClemsonGoogle

def read_data():
    with open("/Users/jtwitty/PycharmProjects/sports_search_engine/offensive_stats_2015.txt") as infile:
        data = infile.readlines()
    return [line.replace('\n','').split(",") for line in data]

def load_data(apps, schema_editor):
    roster = read_data()
    ClemsonGoogle = apps.get_model("clemson_google_app", "ClemsonGoogle")
    for row in roster:
        ClemsonGoogle.objects.create(player_name=row[0], player_position=row[1],jersey_number=row[2],plays_from_scrimmage=row[3],yards_from_scrimmage=row[4],ave_yards_per_play_from_scrimmage=row[5], tds_from_scrimmage=row[6])


class Migration(migrations.Migration):

    dependencies = [
        ('clemson_google_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)

    ]
